
security:

    oauth2:

        authCodeStateCache:
            cacheName: authCodeStateCache
            maxElementsInMemory: 100
            overFlowToDisk: false
            eternal: false
            timeToLiveSeconds: 60
            timeToIdleSeconds: 0

        provider:

            google:
                client:
                    #clientId: configured externally
                    #clientSecret: configured externally
                    authorizationCodeEndpoint: https://accounts.google.com/o/oauth2/v2/auth
                    tokenEndpoint: https://accounts.google.com/o/oauth2/token
                    clientAuthenticationScheme: query
                    scope: email,profile
                    userInfoEndpoint: https://www.googleapis.com/oauth2/v2/userinfo

            github:
                client:
                    #clientId: configured externally
                    #clientSecret: configured externally
                    authorizationCodeEndpoint: https://github.com/login/oauth/authorize
                    tokenEndpoint: https://github.com/login/oauth/access_token
                    clientAuthenticationScheme: form
                    scope: user:email
                    userInfoEndpoint: https://api.github.com/user

            facebook:
                client:
                    #clientId: configured externally
                    #clientSecret: configured externally
                    authorizationCodeEndpoint: https://www.facebook.com/dialog/oauth
                    tokenEndpoint: https://graph.facebook.com/oauth/access_token
                    tokenName: oauth_token
                    authenticationScheme: query
                    clientAuthenticationScheme: form
                    userInfoEndpoint: https://graph.facebook.com/me

server:
    management:
        # actuator endpoints: beans, configprops, env, health, info, mappings, trace
        context-path: /manage

    session:
        cookie:
            # prevent client side scripts from accessing cookies
            http-only: true
            # cookie only sent via tls connection
            secure: true